{{- if .Values.ingress.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-ingress-svc
spec:
  hosts:
  -  {{ .Values.ingress.hostname }}
  -  {{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local
  gateways:
  - gate-https
  - mesh
  http:
  - match:
    - uri:
        {{ if eq .Values.ingress.web false }}
        prefix: /api/{{ .Values.ingress.ingressPath }}
        {{else}}
        prefix: {{ .Values.ingress.ingressPath }}
        {{end}}
      gateways:
        - gate-https
    route:
    - destination:
        host: {{ .Release.Name }}
        port:
          number: {{ .Values.ingress.host.servicePort }}
  - match:
      - gateways:
          - mesh
    route:
      - destination:
          host:  {{ .Release.Name }}
          port:
            number: {{ .Values.ingress.host.servicePort }}
{{- end }}
