name: Helm Chart ECR Pipeline

on:
  push:
    branches:
      - dev

jobs:
  helm-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: "us-east-1" 
      ECR_URL: "123456789012.dkr.ecr.us-east-1.amazonaws.com" 
      CHART_NAME: "web-app" 
      CHART_VERSION: "1.0.0"

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Authenticate to Amazon ECR
      run: |
        aws ecr get-login-password --region ${{ env.AWS_REGION }} | helm registry login --username AWS --password-stdin ${{ env.ECR_URL }}

    - name: Install Helm
      run: |
        curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
        echo "export HELM_EXPERIMENTAL_OCI=1" >> $GITHUB_ENV
      working-directory: ./helm-deploy/services/${{ env.CHART_NAME }}

    - name: Package Helm chart
      run: |
        helm package ${{ env.CHART_NAME }}
        echo "Chart packaged as ${{ env.CHART_NAME }}-${{ env.CHART_VERSION }}.tgz"
      working-directory: ./helm-deploy/services/${{ env.CHART_NAME }}

    - name: Push Helm chart to ECR
      run: |
        helm push ${{ env.CHART_NAME }}-${{ env.CHART_VERSION }}.tgz oci://${{ env.ECR_URL }}
      working-directory: ./helm-deploy/services/${{ env.CHART_NAME }}
